name: Ruby
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:  
      - name: Setup ubuntu
        run: |
          sudo apt-get -yqq install libpq-dev
          sudo apt-get update

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1  
      
      - name: Bundle Install, Create DB and Rubn tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
        run: |
          gem install bundler --version 1.17.3
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare --trace
          bundle exec rspec