name: Ruby
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: root
          POSTGRES_DB: canteen_app_ci_db
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:  
      - name: Setup ubuntu
        run: |
          sudo apt-get -yqq install libpq-dev
          sudo apt-get update

      - name: Set up Ruby
        uses: actions/setup-ruby@v1.114.0

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1  
      
      - name: Bundle Install, Create DB and Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          POSTGRES_USER: root
          POSTGRES_DB: canteen_app_ci_db
          POSTGRES_PASSWORD: root
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:prepare --trace
          bundle exec rspec